[package]
name = "ecies-ed25519"
version = "0.1.0"
authors = ["phayes <patrick.d.hayes@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ECIES on Twisted Edwards Curve25519 using AES-GCM and HKDF-SHA256"
categories = ["cryptography"]
keywords = ["ecies", "encryption", "ed25519", "curve25519", "aes-gcm"]
repository = "https://github.com/phayes/ecies-ed25519"
readme = "README.md"

[dependencies]
rand = '0.7.3'
curve25519-dalek  = "2.0.0"
failure = "0.1.6"
ed25519-dalek = { version = "1.0.0-pre.3" }
zeroize = "1.1.0"

# "ring" feature
ring = { version = "0.16.11", optional = true }

# "pure_rust" feature
aes-gcm = { version = "0.3.0", optional = true}
sha2 = { version = "0.8.1", optional = true}
digest = { version = "0.8.1", optional = true}
hkdf = { version = "0.8.0", optional = true }

[features]
default = ["ring"]
pure_rust = ["aes-gcm",  "sha2", "digest", "hkdf"]
