name: checks

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install tarpaulin
      run: |
        wget https://github.com/xd009642/tarpaulin/releases/download/0.10.2/cargo-tarpaulin-0.10.2-travis.tar.gz
        tar -xf cargo-tarpaulin-0.10.2-travis.tar.gz
        sudo cp cargo-tarpaulin /usr/local/bin
        sudo chmod a+x /usr/local/bin/cargo-tarpaulin

    - name: cargo check
      run: |
        cargo check --no-default-features --features=ring
        cargo check --no-default-features --features=pure_rust
        cargo check --no-default-features --features=ring,serde
        cargo check --no-default-features --features=pure_rust,serde
        cargo clippy --no-default-features --features=ring
        cargo clippy --no-default-features --features=pure_rust
        cargo clippy --no-default-features --features=ring,serde
        cargo clippy --no-default-features --features=pure_rust,serde

    - name: Run Tests
      run: |
        cargo test --no-default-features --features=ring
        cargo test --no-default-features --features=pure_rust
        cargo test --no-default-features --features=ring,serde
        cargo test --no-default-features --features=pure_rust,serde

    - name: Code Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cargo tarpaulin --no-default-features --features=ring,serde --out Xml
        bash <(curl -s https://codecov.io/bash)
        cargo tarpaulin --no-default-features --features=pure_rust,serde --out Xml
        bash <(curl -s https://codecov.io/bash)
